import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function generateResultPDF(data: any): string {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(20)
  doc.setTextColor(124, 111, 205) // Primary color
  doc.text('MockIQ', 14, 22)
  
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text(`Result: ${data.testTitle}`, 14, 32)
  doc.setFontSize(11)
  doc.text(`Student: ${data.studentName}`, 14, 40)
  doc.text(`Date: ${new Date(data.date).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`, 14, 46)

  // Summary Table
  autoTable(doc, {
    startY: 55,
    head: [['Score', 'Correct', 'Wrong', 'Unattempted', 'Time Taken', 'Accuracy']],
    body: [[
      data.score,
      data.totalCorrect,
      data.totalWrong,
      data.totalUnattempted,
      `${Math.floor(data.timeTakenSeconds / 60)}m ${data.timeTakenSeconds % 60}s`,
      `${((data.totalCorrect / data.totalQuestions) * 100).toFixed(1)}%`
    ]],
    headStyles: { fillColor: [124, 111, 205] }
  })

  // Question-wise table
  const tableData = data.questions.map((q: any) => [
    q.questionNo,
    q.userAnswer || '-',
    q.correctAnswer,
    q.userAnswer === q.correctAnswer ? '✓' : (q.userAnswer ? '✗' : '—'),
    q.userAnswer === q.correctAnswer ? `+${data.markingCorrect}` : (q.userAnswer ? `${data.markingWrong}` : '0')
  ])

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 15,
    head: [['Q#', 'Your Answer', 'Correct Answer', 'Status', 'Marks']],
    body: tableData,
    headStyles: { fillColor: [124, 111, 205] }
  })

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(10)
    doc.setTextColor(150)
    doc.text('Generated by MockIQ', doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: 'center' })
  }

  return doc.output('datauristring')
}

export function generateAnswerKeyPDF(data: any): string {
  const doc = new jsPDF()
  
  // Header
  doc.setFontSize(20)
  doc.setTextColor(124, 111, 205)
  doc.text('MockIQ', 14, 22)
  
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text(`Answer Key & Explanations: ${data.testTitle}`, 14, 32)
  
  let yPos = 45

  data.questions.forEach((q: any) => {
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage()
      yPos = 20
    }

    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    const qText = doc.splitTextToSize(`Q${q.questionNo}. ${q.questionText}`, 180)
    doc.text(qText, 14, yPos)
    yPos += (qText.length * 5) + 3

    doc.setFont('helvetica', 'normal')
    doc.text(`A) ${q.optionA}`, 20, yPos); yPos += 5;
    doc.text(`B) ${q.optionB}`, 20, yPos); yPos += 5;
    doc.text(`C) ${q.optionC}`, 20, yPos); yPos += 5;
    doc.text(`D) ${q.optionD}`, 20, yPos); yPos += 7;

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(40, 167, 69) // Green for correct answer
    doc.text(`Correct Answer: ${q.correctAnswer}`, 14, yPos)
    yPos += 7
    
    doc.setTextColor(0, 0, 0)
    if (q.explanation) {
      doc.setFont('helvetica', 'italic')
      const expText = doc.splitTextToSize(`Explanation: ${q.explanation}`, 180)
      doc.text(expText, 14, yPos)
      yPos += (expText.length * 5) + 10
    } else {
      yPos += 5
    }
  })

  // Footer with page numbers
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(10)
    doc.setTextColor(150)
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: 'center' })
  }

  return doc.output('datauristring')
}
